### ISSUE TITLE
subset

### ISSUE THREAD

**Issue by Barman1054** [ayoy/fontedit#1]
Hi,
Great work, easy to use (didn't use but read your webpage). Sometimes I only use subsets of used characters, the used characters in a header f.i. Exporting a subset would make me a fan of this app.
Good luck!

**Comment by ayoy** [comment]
Hey, thanks! I was wondering about that use case actually.

How do you work with a subset of characters? As in that case one has to sacrifice the ASCII-code-to-character mapping (e.g. 'b' is not 'b' anymore when you take out 'a'). I imagine that you just use raw hex codes instead of chars in the code?

**Comment by Barman1054** [comment]
I used fontconvert a few times for small projects. If I remember well, the result is a file with only the data of the selected characters with a lookup table at the end of the file.

**Comment by ayoy** [comment]
Closing this as the subset export functionality is implemented in the [1.1.0 release](https://github.com/ayoy/fontedit/releases/v1.1.0).

**Comment by Barman1054** [comment]
Whow, top!!

____________
vanaf mobiel.
