### ISSUE TITLE
Compiling in Windows 

### ISSUE THREAD

**Issue by ihouses** [ayoy/fontedit#2]
Hello, I have really difficulties to compile the source code in windows. I have downloaded the .NET 2019 in order to get Cmake but after plenty of error nothing can be compiled. Is there any tutorial where I can properly see how to use that tools in windows?

**Comment by ayoy** [comment]
Hey, you don't have to compile the source code in order to use the app on Windows. I have provided an installer on the [releases page](https://github.com/ayoy/fontedit/releases). Download the .exe file and install the app.

If you really want to compile source code, you'd have to get Qt libraries from https://www.qt.io/download-qt-installer, install Qt desktop libraries and Qt Creator. Open the top-level `CMakeLists.txt` in QtCreator and you'll be able to compile and run the app.
