### ISSUE TITLE
Rebuild for macOS 10.13

### ISSUE THREAD

**Issue by focussing** [ayoy/fontedit#8]
Hi!

Thank you for this great app!
I have an iMac late 2011 which runs on macOS 10.13 (newer versions not supported).
Is it possible to rebuild it or are there specific reasons that 10.14 is needed?

Best regards!

**Comment by ayoy** [comment]
Hi Raymond and thanks for reaching out :)

Unfortunately I'm unable to support macOS 10.13 due to C++17 standard used by the app. The C++17 support was introduced only in clang version that's shipped with macOS 10.14, hence the requirement.

Moving back to C++14 would require some significant rewriting and is not what I would really like to do. I hope you understand that.

**Comment by focussing** [comment]
Sure I understand that. I have a lot of fonts on that machine, that's the reason for asking.
No worries!!
